# Generated by Django 3.0.3 on 2020-09-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeMachines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=300)),
                ('water_line_compitable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CoffeePods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type2', models.CharField(max_length=300)),
                ('coffee_flavor', models.TextField()),
                ('pack_size', models.IntegerField()),
            ],
        ),
    ]
