# Generated by Django 3.0.3 on 2020-09-15 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffe_machines_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeFlavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coffee_flavors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffe_machines_app.CoffeePods')),
            ],
        ),
    ]
