# Generated by Django 3.0.3 on 2020-09-15 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffe_machines_app', '0003_auto_20200915_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeepods',
            name='coffee_flavor',
        ),
        migrations.CreateModel(
            name='CoffeeFlavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavors', models.CharField(max_length=200)),
                ('Coffee_flavors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffe_machines_app.CoffeePods')),
            ],
        ),
    ]
