# Generated by Django 3.0.3 on 2020-09-15 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffe_machines_app', '0004_auto_20200915_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffeeflavor',
            old_name='Coffee_flavors',
            new_name='Sizes',
        ),
    ]
