# Generated by Django 3.0.3 on 2020-09-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffe_machines_app', '0005_auto_20200915_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeeflavor',
            name='Sizes',
        ),
        migrations.AddField(
            model_name='coffeeflavor',
            name='sizes',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
