# Generated by Django 3.0.3 on 2020-09-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffe_machines_app', '0012_auto_20200916_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeflavors',
            name='pack_sizes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
