# Generated by Django 3.0.3 on 2020-09-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffe_machines_app', '0013_coffeeflavors_pack_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeepods',
            name='pack_size',
        ),
        migrations.AlterField(
            model_name='coffeeflavors',
            name='pack_sizes',
            field=models.CharField(max_length=100),
        ),
    ]
